feat. bash practices, optimization
+ formatting is a best practice for printf
+ few optimizations, and to avoid piping too much for performance
+ shellcheck friendly

diff --git a/vpsphc b/vpsphc
--- a/vpsphc
+++ b/vpsphc
@@ -1,8 +1,9 @@
 #!/bin/bash
+# shellcheck disable=2164,2129
 
 PUBLIC_IP=$(wget -4qO- ipinfo.io/ip);
 PRIVATE_IP=$(ip addr | grep 'inet' | grep -v inet6 | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | head -1);
-NIC=$(ip -4 route ls | grep default | grep -Po '(?<=dev )(\S+)' | head -1);
+NIC=$(ip -4 route ls | sed -nE '/default/ {s_.*dev.([^ ]*).*_\1_p;q}');
 SERVER=$(wget -4qO- ipinfo.io/org | cut -d' ' -f2-);
 REGION=$(wget -4qO- ipinfo.io/region | sed -e "s/ /-/g");
 DATE=$(date +%m-%d-%Y);
@@ -13,7 +14,7 @@ client_dir="/etc/openvpn/client"
 
 err ()
 {
-	printf "\nTo avoid errors, please install on a fresh vps.\n" && sleep 2 && read -n 1 -s -r -p "Press any key to end " && rm -f vpsphc && exit 1
+	printf '\n%s\n' "To avoid errors, please install on a fresh vps." && sleep 2 && read -n 1 -s -r -p "Press any key to end " && rm -f vpsphc && exit 1
 }
 
 _dropbear ()
@@ -22,10 +23,10 @@ _dropbear ()
 	sed -i "s/NO_START=.*/NO_START=0/" /etc/default/dropbear
 	sed -i "s/DROPBEAR_PORT=.*/DROPBEAR_PORT=143/" /etc/default/dropbear
 	sed -i 's%DROPBEAR_BANNER=.*%DROPBEAR_BANNER="/etc/banner"%' /etc/default/dropbear
-	touch /etc/banner
+	: > /etc/banner
 	systemctl restart dropbear
 	if ! systemctl status dropbear &> /dev/null; then
-		printf "\nFailed to install Dropbear\n" && err
+		printf '\n%s\n' "Failed to install Dropbear" && err
 	fi
 }
 
@@ -37,7 +38,7 @@ _stunnel4 ()
 	sed -i 's/ENABLED=0/ENABLED=1/g' /etc/default/stunnel4
 	systemctl restart stunnel4
 	if ! systemctl status stunnel4 &> /dev/null; then
-		printf "\nFailed to install Stunnel4\n" && err
+		printf '\n%s\n' "Failed to install Stunnel4" && err
 	fi
 }
 
@@ -49,22 +50,21 @@ _squid ()
 	sed -i "s/xxxx/$PUBLIC_IP/g" /etc/squid/squid.conf
 	systemctl restart squid
 	if ! systemctl status squid &> /dev/null; then
-		printf "\nFailed to install Squid\n" && err
+		printf '\n%s\n' "Failed to install Squid" && err
 	fi
 }
 
 _openvpn ()
 {
 	apt install -y gnupg
-	os_release=$(grep "^VERSION_CODENAME=" /etc/os-release | cut -d= -f2)
-	wget -q -O - https://swupdate.openvpn.net/repos/repo-public.gpg|apt-key add -
+	os_release=$(sed -nE '/VERSION_CODENAME=/ {s_.*=(.*)_\1_p;q}' /etc/os-release)
+	wget -q -O - https://swupdate.openvpn.net/repos/repo-public.gpg | apt-key add -
 	printf "deb http://build.openvpn.net/debian/openvpn/stable %s main" "$os_release" > /etc/apt/sources.list.d/openvpn-aptrepo.list
 	apt update
 	apt install -y openvpn openssl ca-certificates
 
-	if [[ -d /etc/openvpn/easy-rsa/ ]]; then
-		rm -rf /etc/openvpn/easy-rsa/
-	fi
+	[[ -d /etc/openvpn/easy-rsa/ ]] && rm -rf /etc/openvpn/easy-rsa/
+	
 	mkdir -p /etc/openvpn/easy-rsa/phc-easyrsa/
 	curl -skL "https://raw.githubusercontent.com/forphc/VPS-Autoscript/main/phc-easyrsa.zip" -o /etc/openvpn/easy-rsa/phc-easyrsa/phc-easyrsa.zip
 	cd /etc/openvpn/easy-rsa/phc-easyrsa/
@@ -89,9 +89,9 @@ _openvpn ()
 	sed -i "s/squidport/$SQUIDPORT/g" "$client_dir"/client_tcp.ovpn
 
 	curl -skL "$GIST/client_udp.ovpn" -o "$client_dir"/client_udp.ovpn
-	printf '\n<ca>\n' >> "$client_dir"/client_udp.ovpn
+	printf '\n%s\n' '<ca>' >> "$client_dir"/client_udp.ovpn
 	cat /etc/openvpn/easy-rsa/phc-easyrsa/pki/ca.crt >> "$client_dir"/client_udp.ovpn
-	printf '</ca>' >> "$client_dir"/client_udp.ovpn
+	printf '%s' '</ca>' >> "$client_dir"/client_udp.ovpn
 	sed -i "s/xxxx/$PUBLIC_IP/g" "$client_dir"/client_udp.ovpn
 	sed -i "s/SERVER&LOC/$SERVER - $REGION/" "$client_dir"/client_udp.ovpn
 	sed -i "s/DATETODAY/$DATE/g" "$client_dir"/client_udp.ovpn
@@ -102,22 +102,22 @@ _openvpn ()
 	printf 1 > /proc/sys/net/ipv4/ip_forward
 	printf 'net.ipv4.ip_forward=1' >/etc/sysctl.d/99-openvpn.conf
 	sysctl -p &> /dev/null
-
-	systemctl enable openvpn-server@server_tcp.service &> /dev/null
-	systemctl enable openvpn-server@server_udp.service &> /dev/null
-	systemctl restart openvpn-server@server_tcp.service
-	systemctl restart openvpn-server@server_udp.service
 	
-	if [ $? -ne 0 ]; then
-		printf "\nFailed to install OpenVPN\n" && err
-	fi	
+	for action in enable restart; do
+		if ! systemctl "$action" openvpn-server@server_tcp.service &> /dev/null; then
+			printf '\n%s\n' "Failed to install OpenVPN" && err
+		fi
+		if ! systemctl "$action" openvpn-server@server_udp.service &> /dev/null; then
+			printf '\n%s\n' "Failed to install OpenVPN" && err
+		fi
+	done
 }
 
 _apache ()
 {
 	curl -skL "$GIST/apache2.sh" -o /tmp/apache2.sh && chmod +x /tmp/apache2.sh && bash /tmp/apache2.sh
 	if ! systemctl status apache2 &> /dev/null; then
-		printf "\nFailed to install Apache2\n" && err
+		printf '\n%s\n' "Failed to install Apache2" && err
 	fi
 }
 
@@ -138,7 +138,7 @@ _webmin ()
 	sed -i "s/ssl=1/ssl=0/" /etc/webmin/miniserv.conf
 	systemctl restart webmin
 	if ! systemctl status webmin &> /dev/null; then
-		printf "\nFailed to install Webmin\n" && err
+		printf '\n%s\n' "Failed to install Webmin" && err
 	fi
 }
 
@@ -163,7 +163,7 @@ _fail2ban ()
 
 _menu_scripts ()
 {
-	curl -skL 'https://raw.githubusercontent.com/forphc/VPS-Autoscript/main/menu.zip' -o /tmp/menu.zip
+	curl -skL "https://raw.githubusercontent.com/forphc/VPS-Autoscript/main/menu.zip" -o /tmp/menu.zip
 	cp /tmp/menu.zip /usr/local/sbin/
 	cd /usr/local/sbin/
 	unzip -q menu.zip
@@ -174,34 +174,31 @@ _menu_scripts ()
 _misc ()
 {
 	# Limit access of users
-	printf "/bin/false\n" >> /etc/shells
-	printf "/usr/sbin/nologin" >> /etc/shells
-
+	printf '%s\n%s' "/bin/false" "/usr/sbin/nologin" >> /etc/shells
+	
 	# Set timezone to GMT+8 PHST
 	timedatectl set-timezone Asia/Manila
 
 	# Disable IPv6
-	cat >> /etc/sysctl.d/99-sysctl.conf << END
-net.ipv6.conf.all.disable_ipv6 = 1
-net.ipv6.conf.default.disable_ipv6 = 1
-net.ipv6.conf.lo.disable_ipv6 = 1
-net.ipv6.conf.eth0.disable_ipv6 = 1
-END
+	cat >> /etc/sysctl.d/99-sysctl.conf <<-END
+	net.ipv6.conf.all.disable_ipv6 = 1
+	net.ipv6.conf.default.disable_ipv6 = 1
+	net.ipv6.conf.lo.disable_ipv6 = 1
+	net.ipv6.conf.eth0.disable_ipv6 = 1
+	END
 
 	# Add neofetch
-	cat > /etc/profile.d/login.sh << END
-clear
-neofetch
-END
+	cat > /etc/profile.d/login.sh <<-END
+	clear
+	neofetch
+	END
 
 	# Cron
 	mkdir /etc/phc
 	curl -skL "$GIST/delexp.sh" -o /etc/phc/delexp.sh
 	chmod +x /etc/phc/delexp.sh
 	crontab -l > mycron
-	printf "SHELL=/bin/bash
-	PATH=/bin:/sbin:/usr/bin:/usr/sbin
-	0 1 * * * /bin/bash /etc/phc/delexp.sh >/dev/null 2>&1 \n\n" >> mycron
+	printf '%s\n%s\n%s\n\n' "SHELL=/bin/bash" "PATH=/bin:/sbin:/usr/bin:/usr/sbin" "0 1 * * * /bin/bash /etc/phc/delexp.sh >/dev/null 2>&1" >> mycron
 	crontab mycron
 	rm mycron
 }
@@ -238,12 +235,12 @@ install_all ()
 _start ()
 {
 	clear
-	printf "\nProceed installation?\n"
+	printf '\n%s\n' "Proceed installation?"
 
 	select option in YES NO
 	do
 		case $option in
-				YES)
+			YES)
 				clear
 				t1=$(date +%s)
 				export DEBIAN_FRONTEND=noninteractive
@@ -255,7 +252,7 @@ _start ()
 				install_all
 				break
 				;;
-				NO)
+			NO)
 				printf "Cancelled, exiting..." && sleep 3
 				clear && exit
 				break
@@ -267,17 +264,16 @@ _start ()
 
 check_system ()
 {
-	OS_RELEASE_ID=$(grep "^ID=" /etc/os-release | cut -d '=' -f 2- | sed 's|"||g')
-	OS_RELEASE_VERSION_ID=$(grep "^VERSION_ID=" /etc/os-release | cut -d '=' -f 2- | sed 's|"||g')
+	OS_RELEASE_ID=$(sed -nE '/^ID=/ {s_.*=(.*)_\1_g;s_\"__g;p}' /etc/os-release)
+	OS_RELEASE_VERSION_ID=$(sed -nE '/VERSION_ID=/ {s_.*=(.*)_\1_g;s_\"__g;p}' /etc/os-release)
 
 	SUPPORTED=false
-	[[ "${OS_RELEASE_ID}" == "debian" && "${OS_RELEASE_VERSION_ID}" == "9" ]] && SUPPORTED=true
-	[[ "${OS_RELEASE_ID}" == "debian" && "${OS_RELEASE_VERSION_ID}" == "10" ]] && SUPPORTED=true
-	[[ "${OS_RELEASE_ID}" == "ubuntu" && "${OS_RELEASE_VERSION_ID}" == "18.04" ]] && SUPPORTED=true
-	[[ "${OS_RELEASE_ID}" == "ubuntu" && "${OS_RELEASE_VERSION_ID}" == "20.04" ]] && SUPPORTED=true
+	if [[ "${OS_RELEASE_ID}" =~ ubuntu|debian ]] && [[ "${OS_RELEASE_VERSION_ID}" =~ 9|10|18\.04|20\.04 ]]; then
+		SUPPORTED=true
+	fi
 
-	if [[ "${SUPPORTED}" == "false" ]]; then
-		printf "OS distribution not supported by this script.\n"
+	if [[ "${SUPPORTED}" != "true" ]]; then
+		printf '%s\n' "OS distribution not supported by this script."
 		exit 1
 	else
 		_start
@@ -285,24 +281,32 @@ check_system ()
 }
 
 # Verify root
-if [[ $(whoami) = root ]]; then
+if [[ "$(id -u)" -eq 0 ]]; then
 	check_system
 else
-	printf "You must be logged in as root before running this script.\n"
+	printf '%s\n' "You must be logged in as root before running this script."
 	exit 1
 fi
 
 
 # Done
 t2=$(date +%s)
-tf=$(( $t2 - $t1 ))
-printf "\n"
-printf "Installation success. \n"
-printf "Time taken: \e[1;32m %s \e[0m \n" "$(date -d@$tf +%Mmin:%Ssec)"
-printf "Access management panel using command: \e[1;32mmenu\e[0m \n"
-printf "Please reboot your system using command, \e[1;32mreboot\e[0m\n\n"
+tf=$(( t2 - t1 ))
+
+while IFS= read -r iter; do
+	printf '%b\n' "${iter}"
+done <<-EOF
+
+Installation success.
+Time taken: \033[1;32m $(date -d@$tf +%Mmin:%Ssec) \033[0m
+Access management panel using command: \033[1;32mmenu\033[0m
+Please reboot your system using command, \033[1;32mreboot\033[0m
+
+EOF
+
 read -n 1 -s -r -p "Press any key to end"
 # clean_up
-rm -f /tmp/apache2.sh
-rm -f /tmp/menu.zip
-rm -f vpsphc && exit
+for clean in /tmp/apache2.sh /tmp/menu.zip vpsphc; do
+	[[ -e "$clean" ]] && rm -f "$clean"
+done
+exit 0
